# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Firebase/Core', '~> 4.13.0'
pod 'Firebase/Auth', '~> 4.13.0'

target 'ReadStory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadStory

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'ReadStoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
