# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

target 'ReadStory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadStory

  target 'ReadStoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReadStory-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadStory-tvOS

  target 'ReadStory-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
